# Para iniciar docker-compose up -d
version: '3.5'

services:
  mariadb:
    build: ./mariadb
    image: mariadb
    container_name: mariadb
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - mariadb-volume:/var/lib/mysql
    networks:
      - mariadb-network
    restart: always

volumes:
  mariadb-volume:

networks:
  mariadb-network:
    driver: bridge
